name: Verify Squashed Commits

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions: {}

jobs:
  verify-squash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false

      - name: Verify commits are squashed
        uses: ./ci_squash
        with:
          max-commits: 1
